### ISSUE TITLE
HTMLtoJSX page is broken

### ISSUE THREAD

**Issue by Daniel15** [reactjs/react-magic#141]
Reported by @gaearon

http://magic.reactjs.net/htmltojsx.htm

**Comment by sujkhnomad** [comment]
+1

**Comment by Daniel15** [comment]
I don't have time to work on it at the moment, but I'm happy to take a pull
request to fix this.

**Comment by ztanner** [comment]
Seems like the issue is that https://facebook.github.io/react/js/live_editor.js references `prop-types` and `create-react-class`, which are not being built/included. I can make a PR to include CDN links since it probably doesn't make sense to bundle it with the `htmltojsx` component. 

Fixed here: https://github.com/reactjs/react-magic/pull/142
