### ISSUE TITLE
cannot find module 'jsdom'

### ISSUE THREAD

**Issue by basarat** [reactjs/react-magic#31]
https://github.com/reactjs/react-magic/blob/d85cf2665282b9b9d71f0ad4637d01deef448f37/src/htmltojsx.js#L148 But it doesn't actually have a dependency on it : https://github.com/reactjs/react-magic/blob/d85cf2665282b9b9d71f0ad4637d01deef448f37/package.json#L10

Refs https://github.com/TypeStrong/atom-typescript/issues/519#issuecomment-128560773

**Comment by Daniel15** [comment]
Sorry about that! I got a pull request to switch from `jsdom` to `jsdom-no-contextify`, but it looks like the `require` statement wasn't updated. Everything still worked when I was testing it, since I still had the old `jsdom` in my `node_modules` (I guess npm doesn't clean up unused modules). I'm still learning the ins and outs of npm :smile:. I'll fix this right now.

**Comment by Daniel15** [comment]
Fixed in 0.2.4.

**Comment by basarat** [comment]
No worries. I got all this code for free soooo :rose: :heart:
